### ISSUE TITLE
comma connect qr code cut off

### ISSUE THREAD

**Issue by 22andrew22** [commaai/openpilot#20878]
the bottom of the qr code is cut off by 2 pixels on the bottom. this is on a fresh 0.8.3 build.

**Comment by pd0wm** [comment]
Fixed in 0.8.4!

**Comment by TKassis** [comment]
The updated Android app did not help, unfortunately. I still can't pair. I emailed support so maybe it can be done manually.

**Comment by pd0wm** [comment]
You probably need both the new app and the fixed qr code in 0.8.4
